
from functools import reduce

s = """OPERATIONEND,24,CLOSE,14,CREATE,12,QUERYSECURITY,32,FSCTL,23,QUERYINFORMATION,22,CLEANUP,13,READ,15,DIRNOTIFY,25,CREATENEWFILE,30,WRITE,16,NAMECREATE,10,SETINFORMATION,17,RENAME,19,RENAMEPATH,27,NAMEDELETE,11,SETDELETE,18,DELETEPATH,26,DIRENUM,20,QUERYEA,34,FLUSH,21,SETSECURITY,31"""
s = s.split(",")
sumx = ""
for i in range(len(s)):
    sumx += ((f"\"{s[i]}\"" if i % 2 == 0 else s[i]) + f": {i},\n")


print(sumx)
